# Generated by Django 3.2 on 2021-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='tag',
            field=models.CharField(default='all', max_length=25),
        ),
    ]
